---
- hosts: all
  become: yes
  tasks:
   - name: encrypt and set password
     command: 
         useradd "{{ my_username }}"; echo "{{ my_password }}" | passwd "{{ my_username }}" --stdin

         
  
    
