---
- hosts: all
  become: yes
  tasks:
   - name: Creating user "{{ uusername }}" with admin access
     user: 
       name: {{ uusername }}
       password: {{ upassword | password_hash('sha512') }}

         
  
    
