---
- hosts: all
  become: yes
  tasks:
   - name: Add user
     user: 
       name: "{{ my_username }}"
       createhome: yes
       password: "{{ my_password }}"
   - name: Force user to change password 
     command:
         chage -d 0 "{{ my_username }}"
  
    
