---
- hosts: all
  become: yes
  tasks:
   - name: User creation
     user: 
       name: "{{ my_username }}"
       shell: /bin/bash
       password: "$6$xyz$B4JYME7IY/cliQN7xfDFXmq87nr/vFeUlUqOVxLSEUFQkYTiGAHhwspgKevfh0DROnfpCkPhG8kXYF9J6AMNI1"

         
  
    
