---
- hosts: all
  become: yes
  tasks:
   - name: Add user
     user: 
       name: "{{ my_username }}"
       createhome: yes
       shell: /bin/bash
   - name: encrypt and set password
     command: 
         password $(echo "{{ my_password }}" | openssl passwd -1 -stdin) "{{ my_username }}"
         
         
  
    
