---
- hosts: all
  become: yes
  tasks:
   - name: Add user
     user: 
       name: "{{ my_username }}"
       createhome: yes
       shell: /bin/bash
   - name: encrypt and set password
     command: 
         echo -e "{{ my_password }}"\n"{{ my_password }}" | passwd linuxuser

         
  
    
