---
- hosts: all
  become: yes
  tasks:
   - name: Add user
     user: 
       name: "{{ my_username }}"
       createhome: yes
       shell: /bin/bash
   - name: encrypt and set password
     command: 
         sudo chpasswd | echo '{{ my_username }}:{{ my_password }}' 

         
  
    
