---
- hosts: all
  become: yes
  tasks:
   - name: Add user
     user: 
       name: "{{ my_username }}"
       createhome: yes
       shell: /bin/bash
   - name: encrypt and set password
     command: 
         useradd -p $(openssl passwd -1 -salt "{{ my_password }}") "{{ my_username }}"
         
         
  
    
