---
- name: check updates
  hosts: all
  gather_facts: true
  
  tasks:
    - name: check for updates
      become: true
      yum: list=updates update_cache=true
      register: yumoutput
    - debug: var=yumoutput
        msg: "{{ yumoutput.results | map(attribute='name') | list }}"
      
