---
- hosts: all
  tasks:
  - name: Update all installed packages using YUM module
    become: true
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status
  - name: Update all security updates
    become: true
    yum:
      name: 'upgrade,security'
      state: latest
      update_cache: yes
